// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:autobridge/domain/entities/favorite_car.dart';
import 'package:autobridge/domain/entities/user_settings.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FavoriteCarAdapter());
    registerAdapter(UserSettingsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FavoriteCarAdapter());
    registerAdapter(UserSettingsAdapter());
  }
}
